"""remove video_path from pending_approvals

Revision ID: 1bc3bb0ceea5
Revises: 30eef01f090a
Create Date: 2026-02-12 20:57:43.807140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc3bb0ceea5'
down_revision: Union[str, Sequence[str], None] = '30eef01f090a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.drop_column('video_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_path', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
